# Generated by Django 5.1.4 on 2024-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
