# Generated by Django 5.1.4 on 2024-12-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('scheduling', '0003_remove_appointment_user'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='categories.categories'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='stores.stores'),
        ),
    ]
